EmployeeArrivalTracker/EmployeeArrivalTracker/Models/Contracts/IPageSettings.cs
namespace EmployeeArrivalTracker.Models.Contracts
{
    public interface IPageSettings<TSorting, TCollection>
    {
        string SearchTerm { get; set; }
        int CurrentPage { get; set; }
        int TotalElements { get; set; }
        TSorting Sorting { get; init; }
        IEnumerable<TCollection> ModelCollection { get; set; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/Contracts/PageSettingsAbstract.cs
namespace InfluencerWannaBe.Models
{
    using System.Collections.Generic;
    using EmployeeArrivalTracker.Models.Contracts;

    public abstract class PageSettingsAbstract<TSorting, TCollection> : IPageSettings<TSorting, TCollection>
    {
        public string SearchTerm { get; set; }
        public int CurrentPage { get; set; } = 1;
        public int TotalElements { get; set; }
        public TSorting Sorting { get; init; }
        public IEnumerable<TCollection> ModelCollection { get; set; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/EmployeeArrival/EmployeeArrival.cs
namespace EmployeeArrivalTracker.Models.EmployeeArrival
{
    public class EmployeeArrival
    {
        public int EmployeeId { get; init; }
        public DateTime When { get; init; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/EmployeeArrival/EmployeeArrivalListingViewModel.cs
using EmployeeArrivalTracker.Data.Models;

namespace EmployeeArrivalTracker.Models.EmployeeArrival
{
    public class EmployeeArrivalListingViewModel
    {
        public int Id { get; init; }
        public string Name { get; init; }
        public string Surname { get; init; }
        public string Role { get; init; }
        public string Manager { get; init; }

        //TO DO maybe cript it GDPR
        public string Email { get; init; }
        public DateTime ArrivedTime { get; init; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/EmployeeArrival/EmployeeArrivalQueryModel.cs
namespace EmployeeArrivalTracker.Models.EmployeeArrival
{
    using InfluencerWannaBe.Models;
    using EmployeeArrivalTracker.Configuration;
    using EmployeeArrivalTracker.Models.EmployeeArrival.Enums;
    using Microsoft.Extensions.Options;

    public class EmployeeArrivalQueryModel : PageSettingsAbstract<EmployeeArrivalSorting, EmployeeArrivalListingViewModel>
    {
        public const int EmployeePerPage = 50;

        public DateTime Date { get; set; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/EmployeeArrival/Enums/EmployeeArrivalSorting.cs
namespace EmployeeArrivalTracker.Models.EmployeeArrival.Enums
{
    public enum EmployeeArrivalSorting
    {
        EmployeeId = 0,
        Name = 1,
        ArrivalTime = 2,
        Role = 3
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/EmployeeArrival/RequestDateModel.cs
namespace EmployeeArrivalTracker.Models.EmployeeArrival
{
    using System.ComponentModel.DataAnnotations;
    public class RequestDateModel
    {
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime Date { get; set; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/EmployeeParse.cs
namespace EmployeeArrivalTracker.Models
{
    public class EmployeeParse
    {
        public int Id { get; init; }
        public int? ManagerId { get; init; }
        public int Age { get; init; }
        public string Role { get; init; }       
        public string Email { get; init; }       
        public string Name { get; init; }        
        public string SurName { get; init; }
        public string[] Teams { get; set; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/ErrorViewModel.cs
namespace EmployeeArrivalTracker.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Models/WebServiceToken.cs
namespace EmployeeArrivalTracker.Models
{
    public class WebServiceToken
    {
        public string Token { get; set; }

        public DateTime When { get; set; }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Controllers/EmployeeArrivalController.cs
namespace EmployeeArrivalTracker.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using EmployeeArrivalTracker.Models.EmployeeArrival;
    using EmployeeArrivalTracker.Services.EmployeeArrival;

    [Route("[controller]")]
    public class EmployeeArrivalController : Controller
    {
        private readonly IEmployeeDataExtractionService _employeeDataExtractor;

        public EmployeeArrivalController(IEmployeeDataExtractionService employeeDataExtractor, ILogger<EmployeeArrivalController> logger)
        {
            _employeeDataExtractor = employeeDataExtractor;
        }
        public IActionResult Employees([FromQuery] EmployeeArrivalQueryModel query, RequestDateModel requestDateModel)
        {
            query = _employeeDataExtractor.QueryService(query, requestDateModel);

            return View(query);
        }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Controllers/HomeController.cs
using EmployeeArrivalTracker.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EmployeeArrivalTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Controllers/SubscribeController.cs
namespace EmployeeArrivalTracker.Controllers
{
    using EmployeeArrivalTracker.Models;
    using EmployeeArrivalTracker.Models.EmployeeArrival;
    using EmployeeArrivalTracker.Services;
    using Microsoft.AspNetCore.Mvc;

    [Route("[controller]")]
    public class SubscribeController : Controller
    {
        private readonly ComunicationService _subscriberService;
        private readonly ILogger _logger;
        private static WebServiceToken _fourthToken = new WebServiceToken();
        private static RequestDateModel _steatelessRequestDate;
        public SubscribeController(ComunicationService subscriberService, ILogger<SubscribeController> logger)
        {
            _logger = logger;
            _subscriberService = subscriberService;
        }

        public IActionResult Subscribe() => this.View(new RequestDateModel());

        [HttpPost]
        public async Task<IActionResult> Subscribe([FromForm]RequestDateModel requestModel)
        {
            try
            {
                if (requestModel.Date == null)
                {
                    this.ModelState.AddModelError(nameof(requestModel.Date), "Date is required");
                    return View(requestModel);
                } 

                var responseToken = await _subscriberService.SubscribeToWebService(requestModel);
                _fourthToken.Token = responseToken.Token;
                _fourthToken.When = responseToken.When;

                if(_fourthToken == null)
                {
                    this.ModelState.AddModelError(nameof(_fourthToken), "WebService connection issue...");
                    return View(requestModel);
                }

            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error while trying to subscribe to WebService: {Error}", ex.Message);
            }

            _steatelessRequestDate = requestModel;
            return RedirectToAction("Employees", "EmployeeArrival", _steatelessRequestDate);
            //return View(requestModel);
        }

        [HttpPost, Route("getdata")]
        public IActionResult GetData([FromBody] List<EmployeeArrival> arrivals)
        {
            var token = Request.Headers["X-Fourth-Token"];

            if (string.IsNullOrEmpty(token) || token != _fourthToken.Token)
            {
                return BadRequest("Token is missing or invalid");
                //Response.StatusCode = 401;
                //RedirectToAction(nameof(EmployeArrivalController.Employees));
            }

            _subscriberService.GetDataFromWebService(arrivals);

            return Ok();
            //Response.StatusCode = 200;
        }
            
    }
}

EmployeeArrivalTracker/EmployeeArrivalTracker/Views/EmployeeArrival/Employees.cshtml
@model EmployeeArrivalQueryModel

@{
    ViewData["Title"] = "Employees ArrivalTime";
}

<form method="get">
    <div class="row mb-5">
        <div class="form-gorup col-md-4">
            <label asp-for="SearchTerm">Search</label>
            <input asp-for="SearchTerm" class="form-control" />
        </div>

        <div class="form-gorup col-md-4">
            <div class="form-group">
                <label asp-for="Sorting">Sort By</label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0" selected>EmployeeId</option>
                    <option value="1">Name</option>
                    <option value="2">ArrivalTime</option>
                    <option value="3">Role</option>
                </select>
            </div>
        </div>

        <div class="form-gorup col-md-3">
            <input type="submit" class="btn btn-primary" value="Filter" />
            <input type="button" value="Update" onclick="location.href='@Url.Action("Employees", "EmployeeArrival", Model.Date)'" />
        </div>
    </div>
</form>

<div class="row">
    <meta name="viewport" content="width=device-width" />
    <table class=\"styled-table\">
        <thead>
            <tr>
                <th>EmployeeId</th>
                <th>Name</th>
                <th>ArrivalTime</th>
                <th>Manager</th>
                <th>Role</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var employee in Model.ModelCollection)
            {
                <tr>
                    <td>@employee.Id</td>
                    <td>@employee.Name</td>
                    <td>@employee.ArrivedTime.Date</td>
                    <td>@employee.Manager</td>
                    <td>@employee.Role</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@{
    var previusPage = Model.CurrentPage - 1;
    if (previusPage < 1)
    {
        previusPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalElements / EmployeeArrivalQueryModel.EmployeePerPage);
}

<div class="row">
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="EmployeeArrival"
           asp-action="Employees"
           asp-route-currentPage="@(previusPage)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">Previous</a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-primary float-lg-right @(Model.CurrentPage == maxPage ? "disabled" : string.Empty)"
           asp-controller="EmployeeArrival"
           asp-action="Employees"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@((int)Model.Sorting)">Next</a>
    </div>
</div>

EmployeeArrivalTracker/EmployeeArrivalTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EmployeeArrivalTracker/EmployeeArrivalTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeArrivalTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeArrivalTracker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeArrivalTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subscribe" asp-action="Subscribe">GetData</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmployeeArrivalTracker/EmployeeArrivalTracker/Views/Subscribe/Subscribe.cshtml
@model RequestDateModel

@{
    ViewData["Title"] = "Employee Arrival";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
            <form method="post" enctype="multipart/form-data">

                <div>@Html.ValidationSummary(false, "", new { @class = "validation-summary-errors" })</div>

                <div class="btncontainer">
                    <label asp-for="Date">Date</label>
                    <input asp-for="Date" asp-format="{0:yyyy-MM-dd}" class="form-control" value="">
                    @*<span asp-validation-for="Date" class="small text-danger"></span>*@
                    <br />
                </div>

                <input class="btn btn-primary" type="submit" value="Search">
            </form>
        </div>
    </div>
</div>